server:
  port: 8080
  servlet:
    context-path: /api
spring:
  application:
    name: juice-pic-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://43.155.219.134:3306/juicePicture
    username: root
    password: 2004723zwJ@

